### ISSUE TITLE
fortune -m <TOPIC> works fine to the terminal screen; redirected to a file it repeats each fortune found many time

### ISSUE THREAD

**Issue by IF-Rock** [shlomif/shlomi-fish-homepage#14]
fortune -m <TOPIC> works fine to the terminal screen; redirected to a fail it repeats each fortune found many time

v3.22 on Cygwin

**Comment by IF-Rock** [comment]
"fail" -> file

**Comment by shlomif** [comment]
Hi @IF-Rock ! This seems like an issue in fortune-mod while this is my homesite/personal issue tracker. Anyway, `fortune -m $'Wiker' > out.txt` and `fortune -m $'lack of a slash' > out.txt` only give a single result in `out.txt` on fedora 41beta x86-64 (with fortune-mod git-master).

Can you provide a github actions' script (or similar) which reproduces the issue?

**Comment by shlomif** [comment]
@IF-Rock : hi, it seems to work fine here too: https://github.com/shlomif/fortune-mod/actions/runs/11118906075/job/30893249904

**Comment by shlomif** [comment]
@IF-Rock : hi. please respond

**Comment by shlomif** [comment]
Closing due to lack of response.
