### ISSUE TITLE
XML::LibXML - cannot be installed on macOS BigSur

### ISSUE THREAD

**Issue by irinazpopova** [shlomif/shlomi-fish-homepage#6]
I've been successfully using XML::LibXML module for a while on macOS. 

Now, when I try to install it on a new machine with macOS BigSur, in "make test" I get multiple errors of the kind:

t/00-report-prereqs.t .............................. ok   
t/01basic.t ........................................ Can't load '/Users/lockit/Desktop/TESTS_Irina/XML-LibXML-2.0204/blib/arch/auto/XML/LibXML/LibXML.bundle' for module XML::LibXML: dlopen(/Users/lockit/Desktop/TESTS_Irina/XML-LibXML-2.0204/blib/arch/auto/XML/LibXML/LibXML.bundle, 0x0002): symbol '_xmlFree' not found, expected in flat namespace by '/Users/lockit/Desktop/TESTS_Irina/XML-LibXML-2.0204/blib/arch/auto/XML/LibXML/LibXML.bundle' at /System/Library/Perl/5.28/darwin-thread-multi-2level/DynaLoader.pm line 197.
 at /Users/lockit/Desktop/TESTS_Irina/XML-LibXML-2.0204/blib/lib/XML/LibXML.pm line 156.
BEGIN failed--compilation aborted at /Users/lockit/Desktop/TESTS_Irina/XML-LibXML-2.0204/blib/lib/XML/LibXML.pm line 156.
Compilation failed in require at t/01basic.t line 6.

And the module cannot be installed. 

Attached is also the log from the "make" command.

Any hints what I am missing and how to fix?

Thanks,
Irina

[LibXML_MakeLog.txt](https://github.com/shlomif/shlomi-fish-homepage/files/5820724/LibXML_MakeLog.txt)
[LibXML_MakeTestLog.txt](https://github.com/shlomif/shlomi-fish-homepage/files/5820725/LibXML_MakeTestLog.txt)

**Comment by shlomif** [comment]
Hi @irinazpopova ! Perhaps try to use perlbrew/etc: https://metacpan.org/pod/App::perlbrew .

Mac OS X kinda sucks.

Thanks!

**Comment by irinazpopova** [comment]
Looks like it's an issue with Apple's dynamic linker as described here:

https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/381.

I installed the suggested **ExtUtils-MakeMaker-7.58** module and this solved the initial issue.

However, now there is a new error on **make**: 

"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- LibXML.bs blib/arch/auto/XML/LibXML/LibXML.bs 644 cc -c -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Wno-error=implicit-function-declaration -Os -DVERSION="2.0206" -DXS_VERSION="2.0206" "-I/System/Library/Perl/5.28/darwin-thread-multi-2level/CORE" -DHAVE_UTF8 Av_CharPtrPtr.c Av_CharPtrPtr.c:6:10: fatal error: 'EXTERN.h' file not found #include "EXTERN.h"

Any clue?

Thanks

**Comment by shlomif** [comment]
> Looks like it's an issue with Apple's dynamic linker as described here:
> 
> [Perl-Toolchain-Gang/ExtUtils-MakeMaker#381](https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/381).
> 
> I installed the suggested **ExtUtils-MakeMaker-7.58** module and this solved the initial issue.
> 
> However, now there is a new error on **make**:
> 
> "/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- LibXML.bs blib/arch/auto/XML/LibXML/LibXML.bs 644 cc -c -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -g -pipe -fno-strict-aliasing -fstack-protector-strong -DPERL_USE_SAFE_PUTENV -Wno-error=implicit-function-declaration -Os -DVERSION="2.0206" -DXS_VERSION="2.0206" "-I/System/Library/Perl/5.28/darwin-thread-multi-2level/CORE" -DHAVE_UTF8 Av_CharPtrPtr.c Av_CharPtrPtr.c:6:10: fatal error: 'EXTERN.h' file not found #include "EXTERN.h"
> 
> Any clue?
> 
> Thanks

Any luck? The C include path may be lacking.

**Comment by shlomif** [comment]
@irinazpopova : hi! Ping.

**Comment by shlomif** [comment]
also see https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html
