### ISSUE TITLE
Meaning of "Rind"

### ISSUE THREAD

**Issue by netbsdis** [shlomif/shlomi-fish-homepage#7]
Hello,

on https://www.shlomifish.org/meta/FAQ/#origin_of_rindolf you wonder about the meaning of "Rind". In German, it means cattle (as in Bos Taurus).

Regards,
   -is

**Comment by shlomif** [comment]
Corrected in https://github.com/shlomif/shlomi-fish-homepage/commit/300946c248779e9c2b273d51f395a1db200b2897 - thanks!
