### ISSUE TITLE
Freecell solver page giving error

### ISSUE THREAD

**Issue by gregr-ni** [shlomif/shlomi-fish-homepage#8]
https://fc-solve.shlomifish.org/js-fc-solve/text/ gives "GET not supported for current URL."

**Comment by shlomif** [comment]
Hi!

> Chrome Version 92.0.4515.159 (64-bit) on Windows 10 Build 18363
> It does work in Edge on the same machine.

I see. Chrome is not FOSS as opposed to chromium or firefox. moreover, Given how much Windows Update and antiviruses are atrocious, it is a miracle anything works on mswindows at all: https://www.shlomifish.org/humour/bits/facts/Windows-Update/ .

**Comment by shlomif** [comment]
Hi @gregr-ni !

> What news were you expecting? Your last reply felt like you were criticizing my choice of software. 

I apologise for that.

> I did just try it and it seems to be working in Chrome again. Not sure if you did something or its related to changes in Chrome.

That's great and what I wanted to hear,
